// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/applications/[track]" | "/admin/blog" | "/admin/contact-submissions" | "/admin/employers" | "/admin/login" | "/admin/programmes/[track]" | "/admin/programmes/[track]/[slug]" | "/admin/programmes/[track]/new" | "/admin/settings" | "/admin/stats" | "/admin/success-stories" | "/admin/testimonials" | "/admin/video-testimonials" | "/blog" | "/blog/[slug]" | "/bootcamps" | "/bootcamps/[slug]" | "/business" | "/certifications" | "/certifications/[slug]" | "/community" | "/consultation" | "/contact" | "/hire" | "/outcomes" | "/programmes" | "/programmes/[slug]" | "/reviews" | "/success-stories"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/applications/[track]": { "track": string; }
  "/admin/blog": {}
  "/admin/contact-submissions": {}
  "/admin/employers": {}
  "/admin/login": {}
  "/admin/programmes/[track]": { "track": string; }
  "/admin/programmes/[track]/[slug]": { "track": string; "slug": string; }
  "/admin/programmes/[track]/new": { "track": string; }
  "/admin/settings": {}
  "/admin/stats": {}
  "/admin/success-stories": {}
  "/admin/testimonials": {}
  "/admin/video-testimonials": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/bootcamps": {}
  "/bootcamps/[slug]": { "slug": string; }
  "/business": {}
  "/certifications": {}
  "/certifications/[slug]": { "slug": string; }
  "/community": {}
  "/consultation": {}
  "/contact": {}
  "/hire": {}
  "/outcomes": {}
  "/programmes": {}
  "/programmes/[slug]": { "slug": string; }
  "/reviews": {}
  "/success-stories": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
