// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(panel)/applications/[track]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/applications/[track]">> = Specific
  const handler = {} as typeof import("../../../app/admin/(panel)/applications/[track]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(panel)/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog">> = Specific
  const handler = {} as typeof import("../../../app/admin/(panel)/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(panel)/contact-submissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/contact-submissions">> = Specific
  const handler = {} as typeof import("../../../app/admin/(panel)/contact-submissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(panel)/employers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/employers">> = Specific
  const handler = {} as typeof import("../../../app/admin/(panel)/employers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(panel)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/(panel)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(panel)/programmes/[track]/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/programmes/[track]/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/admin/(panel)/programmes/[track]/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(panel)/programmes/[track]/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/programmes/[track]/new">> = Specific
  const handler = {} as typeof import("../../../app/admin/(panel)/programmes/[track]/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(panel)/programmes/[track]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/programmes/[track]">> = Specific
  const handler = {} as typeof import("../../../app/admin/(panel)/programmes/[track]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(panel)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../app/admin/(panel)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(panel)/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/stats">> = Specific
  const handler = {} as typeof import("../../../app/admin/(panel)/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(panel)/success-stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/success-stories">> = Specific
  const handler = {} as typeof import("../../../app/admin/(panel)/success-stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(panel)/testimonials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/testimonials">> = Specific
  const handler = {} as typeof import("../../../app/admin/(panel)/testimonials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(panel)/video-testimonials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/video-testimonials">> = Specific
  const handler = {} as typeof import("../../../app/admin/(panel)/video-testimonials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/bootcamps/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bootcamps/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/bootcamps/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/bootcamps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bootcamps">> = Specific
  const handler = {} as typeof import("../../../app/bootcamps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/business/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/business">> = Specific
  const handler = {} as typeof import("../../../app/business/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/certifications/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/certifications/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/certifications/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/certifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/certifications">> = Specific
  const handler = {} as typeof import("../../../app/certifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community">> = Specific
  const handler = {} as typeof import("../../../app/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/consultation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consultation">> = Specific
  const handler = {} as typeof import("../../../app/consultation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/hire/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hire">> = Specific
  const handler = {} as typeof import("../../../app/hire/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/outcomes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/outcomes">> = Specific
  const handler = {} as typeof import("../../../app/outcomes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/programmes/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programmes/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/programmes/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/programmes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programmes">> = Specific
  const handler = {} as typeof import("../../../app/programmes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews">> = Specific
  const handler = {} as typeof import("../../../app/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/success-stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/success-stories">> = Specific
  const handler = {} as typeof import("../../../app/success-stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../app/admin/(panel)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/(panel)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
